### ISSUE TITLE
运行卡死情况

### ISSUE THREAD

**Issue by rab3it** [j1anFen/shiro_attack#2]
你好，我在运行的时候初次检测到shiro存在并可以成功执行命令
（其他的shiro工具都利用不成，楼主的可以）
但是我在第二次检测的时候，检测不出来了
并且一直在跑key，然后就卡住了
不知道楼主遇到过没

**Comment by j1anFen** [comment]
目前发现jdk1.7 windows存在这个问题。 由于我工具写的是POST请求获取命令有可能存在第二次执行失败。可以用xray试试。

**Comment by rab3it** [comment]
```
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```
这是我的环境（macos）
确实是第二次会失败,第一次没事

**Comment by j1anFen** [comment]
是使用1.4的工具吗，之前更新了一次。修复了一些执行bug。tomcat7是存在这个问题。

**Comment by rab3it** [comment]
是，之前的16.5 MB
原来前两天更新了0.0
