### ISSUE TITLE
reGeorg的内存马可否改成这个项目的

### ISSUE THREAD

**Issue by liketimo** [j1anFen/shiro_attack#4]
项目中的reGeorg不能用Cookie去连接，目前遇到了一个站对所有Servlet都会做登陆校验拦截，我Cookie有了就是不能连接....
建议换成这个项目的：https://github.com/L-codes/Neo-reGeorg

**Comment by liketimo** [comment]
最新问题：有Cookie了，但是regeorg有https证书错误并且无法忽略，再次建议换成这个项目的：https://github.com/L-codes/Neo-reGeorg

**Comment by ethusans** [comment]
请问您运行jar包不会报错吗，我这报错和 issues 9 一样

**Comment by j1anFen** [comment]
已添加Neo-reGeorg
