### ISSUE TITLE
关于内存马注入提示一些小建议

### ISSUE THREAD

**Issue by like98k** [j1anFen/shiro_attack#6]
点击内存马注入之前，可以加一个检测该路径是否已经被注入，若已经被注入提示注入成功或者无法注入，而不是提示注入失败。

一种情况就是，在内存马注入成功之后再继续点击注入，会提示注入失败（因为本身注入内存马有时候需要多次请求）。

**Comment by j1anFen** [comment]
注入失败更换路径就可以重复注入相同马，因为失败时候可能路径已经写入内存了，一般造成这样手动换路径就可以了。
